runtime: python37
entrypoint: gunicorn -b :$PORT main:app

handlers:
    - url: /static
      static_dir: public
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto
