runtime: python37
entrypoint: gunicorn -b :$PORT main:app
# If the path is empty, show static index.html file
handlers:
    - url: /static
      static_dir: public
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto
